In [1]:
import tensorflow as tf
import pickle
import pandas as pd
from tensorflow.keras.models import load_model
import numpy as np

WARNING:tensorflow:From c:\Users\ragha\Downloads\projects\Ann\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [2]:
# Load the Ann,Scaler  and Onhe hot encoding file
model=load_model('model.h5')


##load encoder and scaler

with open('labelEncoder.pkl','rb') as file:
    labelEncoder=pickle.load(file)

with open('OneHotEncoder_geo.pkl','rb') as file:
    OneHotEncoder_geo=pickle.load(file)

with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

WARNING:tensorflow:From c:\Users\ragha\Downloads\projects\Ann\venv\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

In [11]:
# Example input data 
input_data={
    'CreditScore':600,
    "Geography":"France",
    "Gender":"Male",
    "Age":40,
    "Tenure":3,
    "Balance":6000,
    "NumOfProducts":2,
   	"HasCrCard":1,
    "IsActiveMember":1,
    "EstimatedSalary":5000
}

In [12]:
geo_encoder=OneHotEncoder_geo.transform([[input_data['Geography']]]).toarray()

geo_encoder_df=pd.DataFrame(geo_encoder,columns=OneHotEncoder_geo.get_feature_names_out(['Geography']))
geo_encoder_df

c:\Users\ragha\Downloads\projects\Ann\venv\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [13]:
input_df=pd.DataFrame([input_data])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,6000,2,1,1,5000

In [14]:
input_df['Gender']=labelEncoder.fit_transform(input_df['Gender'])
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,0,40,3,6000,2,1,1,5000

In [15]:
input_data=pd.concat([input_df.drop("Geography",axis=1),geo_encoder_df],axis=1)
input_data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,0,40,3,6000,2,1,1,5000,1.0,0.0,0.0

In [16]:
input_Scaled=scaler.transform(input_data)
input_Scaled

array([[-0.53598516, -1.09499335,  0.10479359, -0.69539349, -1.12240462,
         0.80843615,  0.64920267,  0.97481699, -1.65923237,  1.00150113,
        -0.57946723, -0.57638802]])

In [17]:
## Predict 
prediction=model.predict(input_Scaled)
prediction

1/1 [==============================] - 2s 2s/step

array([[0.2146809]], dtype=float32)

In [19]:
if prediction>0.5:
    print("the customer is  likely to churn.")
else:
    print("the customer is not likely to churn ")

the customer is not likely to churn